version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static 
      
  frontend:
    image: nginx:alpine
    volumes:
      - ./static:/usr/share/nginx/html/static
      - ./templates:/usr/share/nginx/html/templates
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"  # Map port 8080 on your host machine to port 80 on the container
    depends_on:
      - backend
